# Generated by Django 4.0 on 2026-03-09 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='MA', max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('lat', models.FloatField(default=42.3382)),
                ('lng', models.FloatField(default=-71.153)),
                ('property_type', models.CharField(default='Apartment', max_length=50)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('sqft', models.PositiveIntegerField(default=0)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('monthly_rent', models.PositiveIntegerField()),
                ('utilities_included', models.BooleanField(default=False)),
                ('estimated_utilities', models.PositiveIntegerField(default=0)),
                ('security_deposit', models.PositiveIntegerField(default=0)),
                ('broker_fee', models.PositiveIntegerField(default=0)),
                ('application_fee', models.PositiveIntegerField(default=0)),
                ('lease_type', models.CharField(default='Sublease', max_length=50)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('landlord_approval_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('rented', 'Rented')], default='available', max_length=20)),
                ('parking', models.BooleanField(default=False)),
                ('shared', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('has_stairs', models.BooleanField(default=True)),
                ('furnished', models.BooleanField(default=False)),
                ('laundry', models.CharField(default='In-Building', max_length=50)),
                ('amenities', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('images', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auth.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='perchapp.listing')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='auth.user')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=20)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('profile_image', models.URLField(blank=True, default='https://i.pravatar.cc/150?img=1')),
                ('verified', models.BooleanField(default=True)),
                ('role', models.CharField(default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='perchapp.listing')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='auth.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='perchapp.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('requested_from', models.DateField()),
                ('requested_to', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='auth.user')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='perchapp.listing')),
            ],
        ),
    ]
